out_dir: results/deepsnap-cluster-pp
dataset:
  format: PyG
  name: cluster
  task: graph
  task_type: classification
  node_encoder: False
  node_encoder_name: Atom
  edge_encoder: False
  edge_encoder_name: Bond
  dir: /home/uz1/graph-data---pathmnist-16-32-128-UC_False.h5
train:
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
  sampler: full_batch
model: 
  type: gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 1
  layers_mp: 2
  layers_post_mp: 3
  dim_inner: 512
  layer_type: sageconv
  stage_type: skipconcat
  batchnorm: True
  act: prelu
  dropout: 0.2
  agg: mean
  normalize_adj: False
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 600
